name: mechido
description: A one-stop solution for all mechanics and users
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Backend & Authentication
  supabase_flutter: ^2.0.0
  supabase: ^2.0.0
  
  # Maps & Location
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  location: ^5.0.3
  flutter_polyline_points: ^2.0.0
  
  # Payment
  razorpay_flutter: ^1.3.5
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # Utils
  intl: ^0.18.1
  url_launcher: ^6.2.2
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  
  # Networking
  dio: ^5.3.3
  connectivity_plus: ^5.0.2
  
  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Carousel Slider
  carousel_slider: ^5.0.0
  add_to_cart_animation: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/splash_bg.jpg
    - assets/images/app_logo.png
    - assets/images/login_illustration.png
    - assets/images/signup_illustration.png
    # Home screen banners and car image
    - assets/images/banner_ac.png
    - assets/images/banner_tyre.png
    - assets/images/banner_wash.png
    - assets/images/car_avatar.png
    - assets/images/mechanic1.jpg
    - assets/images/mechanic2.jpg
    - assets/images/mechanic3.jpg
    - assets/images/mechanic4.jpg
    - assets/images/mechanic5.jpg
    - assets/images/garage1_bg.jpg
    - assets/images/garage2_bg.jpg
    - assets/images/garage3_bg.jpg
    - assets/images/garage4_bg.jpg
    - assets/images/garage5_bg.jpg
    # Home screen service and quick action icons
    - assets/icons/car_details.png
    - assets/icons/book_service.png
    - assets/icons/booking_details.png
    - assets/icons/share_app.png
    - assets/icons/oil_change.png
    - assets/icons/brake_pad.png
    - assets/icons/battery.png
    - assets/icons/flat_tire.png
    - assets/icons/ac_service.png
    - assets/icons/engine_diag.png
    - assets/icons/periodic_service.png
    - assets/icons/towing.png
    - assets/icons/denting.png
    - assets/icons/suspension.png
    - assets/icons/washing.png
    - assets/icons/other_complaints.png
    - assets/icons/empty_cart.png
    - assets/icons/google-logo.png
    - assets/animations/payment_success.json
    - assets/animations/payment_failed.json
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700 